name: Publish API Docs with redoc
run-name: ${{ github.actor }} is publishing API Docs with redoc 🚀
on: [workflow_dispatch]
jobs:
  Publish-API-Docs:
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: ./gradlew generateOpenApiDocs --no-daemon
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle build/openapi.yaml -o docs/index.html'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2